apiVersion: v1
kind: Service
metadata:
  name: hfi-frontend
  namespace: hfi-prod
  labels:
    app: hfi-frontend
spec:
  type: NodePort

  selector:
    app: hfi-frontend

  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
