apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hfi-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<ORG>/hfi-k8s-prod.git
    targetRevision: main
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true