apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hfi-frontend-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gulbadin1171/HFI-K8S_Manifest-Prod.git
    targetRevision: main
    path: frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: hfi-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
